-- MySQL Script generated by MySQL Workbench
-- 06/24/16 21:47:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alien_abductors
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alien_abductors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alien_abductors` DEFAULT CHARACTER SET utf8 ;
USE `alien_abductors` ;

-- -----------------------------------------------------
-- Table `alien_abductors`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alien_abductors`.`locations` (
  `id` char(36) NOT NULL,
  `State` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Zipcode` VARCHAR(15) NULL,
  `Address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alien_abductors`.`Privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alien_abductors`.`privileges` (
  `id` char(36) NOT NULL,
  `Admin` TINYINT(1) NOT NULL,
  `User` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alien_abductors`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alien_abductors`.`members` (
  `id` char(36) NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Age` TINYINT NULL,
  `location_id` char(36) NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(45) NOT NULL,
  `privilege_id` char(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE(`Username`),
  UNIQUE(`Email`),
  INDEX `location_idx` (`location_id` ASC),
  INDEX `Privlage_idx` (`privilege_id` ASC),
	CONSTRAINT `location` 
	FOREIGN KEY (`location_id`) 
	REFERENCES `alien_abductors`.`locations`(`id`) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
  CONSTRAINT `privilege` 
	FOREIGN KEY (`privilege_id`) 
	REFERENCES `alien_abductors`.`privileges`(`id`) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `alien_abductors`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alien_abductors`.`experiences` (
  `id` char(36) NOT NULL,
  `Exp_Name` VARCHAR(45) NOT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE(`Exp_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alien_abductors`.`Exp_Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alien_abductors`.`exp_reviews` (
  `id`char(36) NOT NULL,
  `Review` TEXT(1000) NULL,
  `Exp_Rating` TINYINT(5) NULL,
  `member_id` char(36) NOT NULL,
  `experience_id` char(36) NOT NULL,
  `Recommend` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `Member_id_idx` (`member_id` ASC),
  INDEX `Exp_id_idx` (`experience_id` ASC),
  CONSTRAINT `member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `alien_abductors`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `experience_id`
    FOREIGN KEY (`experience_id`)
    REFERENCES `alien_abductors`.`experiences` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


